/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TwitterApp;

import static TwitterApp.Home.conexao;
import static TwitterApp.Home.home;
import java.awt.MediaTracker;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import twitter4j.Status;
import twitter4j.TwitterException;
import twitter4j.User;

/**
 *
 * @author adao-
 */
public class TelaUsuario extends javax.swing.JDialog {
    TwitterFuncao tweetar = new TwitterFuncao();
    List<User> lista;
    User user;
    int i = 0;
  /**
     * Creates new form TelaUsuario
     */
    public TelaUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void imagem(User user) {
        String ima = user.getBiggerProfileImageURL();
        // inicializa a imagem URL dentro de um objeto ImageIcon
        URL urlImg = null;
        try {
            urlImg = new URL(ima);
        } catch (MalformedURLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        ImageIcon imgIcon = new ImageIcon(urlImg);
        // faz o preload da imagem
        while (imgIcon.getImageLoadStatus() == MediaTracker.LOADING);

        // injeta o icone no label
        Jimagem.setIcon(imgIcon);
    }
     
    public void tela(User user) throws TwitterException {
        lista = tweetar.Seguindo(conexao, conexao.showUser(conexao.getScreenName()));
        i = 0;
        while (i < lista.size()) {
            if (user.getId() == lista.get(i).getId()) {
                jdeixar.setEnabled(true);
                break;
            } else {
                jseguir.setEnabled(true);
            }
            i++;
        }
    }
      
    public void PreencherTime(User user) throws TwitterException {
        tela(user);
        this.user = user;
        List<Status> statuses = null;

        statuses = tweetar.Timeline(conexao, user);

        for (int i = 0; i < statuses.size(); i++) {
            Status status = statuses.get(i);
            Jtimeline.append(status.getUser().getName() +  " : " + status.getText() + "\n");
            }
        
    }
    
    public void Nome1(User usuario) throws TwitterException {
        Jseguindo.setText("<html>Seguindo<br>" + usuario.getFriendsCount());
        Jseguidores.setText("<html>Seguidores<br>" + usuario.getFollowersCount());
        Jtweets.setText("<html>Tweets<br>" + usuario.getStatusesCount());
        Jnome.setText(usuario.getName());
        Jnome2.setText(usuario.getScreenName());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Jnome = new javax.swing.JLabel();
        Jtweets = new javax.swing.JButton();
        Jseguindo = new javax.swing.JButton();
        Jseguidores = new javax.swing.JButton();
        Jnome2 = new javax.swing.JLabel();
        Jimagem = new javax.swing.JLabel();
        jseguir = new javax.swing.JButton();
        jdeixar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Jtimeline = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Twitter for Java");
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Jnome.setText("Nome");

        Jtweets.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Jtweets.setText("Tweets");

        Jseguindo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Jseguindo.setText("Seguindo");
        Jseguindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JseguindoActionPerformed(evt);
            }
        });

        Jseguidores.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Jseguidores.setText("Seguidor");
        Jseguidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JseguidoresActionPerformed(evt);
            }
        });

        Jnome2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Jnome2.setText("jLabel1");

        jseguir.setText("Seguir");
        jseguir.setEnabled(false);
        jseguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jseguirActionPerformed(evt);
            }
        });

        jdeixar.setText("Deixar de Seguir");
        jdeixar.setEnabled(false);
        jdeixar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdeixarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Jtweets, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(Jseguindo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(Jseguidores, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Jimagem, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jnome2)
                            .addComponent(Jnome, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jseguir, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jdeixar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Jnome, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jnome2))
                    .addComponent(Jimagem, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jtweets)
                    .addComponent(Jseguindo)
                    .addComponent(Jseguidores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jseguir)
                    .addComponent(jdeixar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Jtimeline.setEditable(false);
        Jtimeline.setColumns(20);
        Jtimeline.setRows(5);
        Jtimeline.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(Jtimeline);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(25, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(195, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(291, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JseguindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JseguindoActionPerformed
      //  lista=tweetar.Seguindo(conexao);
        //      jTextseguindo.setText(" " );
        for(i=0;i<lista.size();i++){
            user =lista.get(i);
            //    jTextseguindo.append(user.getScreenName()+"\n");
        }
    }//GEN-LAST:event_JseguindoActionPerformed

    private void JseguidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JseguidoresActionPerformed
        lista=null;
    //    lista=tweetar.Seguidores(conexao);
        //   jTextseguidores.setText(" " );
        for(i=0;i<lista.size();i++){
            user =lista.get(i);
            // jTextseguidores.append(user.getScreenName()+"\n");
        }
    }//GEN-LAST:event_JseguidoresActionPerformed

    private void jseguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jseguirActionPerformed
        try {
            tweetar.Seguir(conexao,user.getScreenName());
            jseguir.setEnabled(false);
            jdeixar.setEnabled(true);
            
            JOptionPane.showMessageDialog(null, "Voce esta seguindo : "+user.getScreenName());
        } catch (TwitterException ex) {
            JOptionPane.showMessageDialog(null, "ERRO AO SEGUIR : "+user.getScreenName());
        }
    }//GEN-LAST:event_jseguirActionPerformed
   
    private void jdeixarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdeixarActionPerformed
        try {
            tweetar.Deixar(conexao, user.getScreenName());
            jseguir.setEnabled(true);
            jdeixar.setEnabled(false);
                       
            JOptionPane.showMessageDialog(null, "Voce deixou de seguir : " + user.getScreenName());
        } catch (TwitterException ex) {
            JOptionPane.showMessageDialog(null, "ERRO AO SEGUIR : " + user.getScreenName());
        }
    }//GEN-LAST:event_jdeixarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaUsuario dialog = new TelaUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jimagem;
    private javax.swing.JLabel Jnome;
    private javax.swing.JLabel Jnome2;
    private javax.swing.JButton Jseguidores;
    private javax.swing.JButton Jseguindo;
    private javax.swing.JTextArea Jtimeline;
    private javax.swing.JButton Jtweets;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jdeixar;
    private javax.swing.JButton jseguir;
    // End of variables declaration//GEN-END:variables
}
