package TwitterApp;

import static TwitterApp.Home.conexao;
import java.awt.MediaTracker;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import twitter4j.Relationship;
import twitter4j.Status;
import twitter4j.TwitterException;
import twitter4j.User;

public class TelaUsuario extends javax.swing.JDialog {

    TwitterFuncao tweetar = new TwitterFuncao();
    List<User> lista;
    User user;
    int i = 0;

    /**
     * Creates new form TelaUsuario
     */
    public TelaUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void imagem(User user) {
        String ima = user.getBiggerProfileImageURL();
        // inicializa a imagem URL dentro de um objeto ImageIcon
        URL urlImg = null;
        try {
            urlImg = new URL(ima);
        } catch (MalformedURLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        ImageIcon imgIcon = new ImageIcon(urlImg);
        // faz o preload da imagem
        while (imgIcon.getImageLoadStatus() == MediaTracker.LOADING);

        // injeta o icone no label
        Jimagem.setIcon(imgIcon);
    }

    public boolean verificaSeguidor(User user) throws TwitterException {
        Relationship relacao;
        relacao = conexao.showFriendship(conexao.getScreenName(), user.getScreenName());

        if (relacao.isSourceFollowingTarget()) {
            //System.out.println("Estou seguindo");
            jseguir.setEnabled(false);
            jdeixar.setEnabled(true);
            return true;
        } else {
            //System.out.println("Não Estou seguindo");
            jseguir.setEnabled(true);
            jdeixar.setEnabled(false);
            return false;
        }
    }

    public void PreencherTime(User user) throws TwitterException {
        boolean estouSeguindo = verificaSeguidor(user);

        if (user.isProtected() && !estouSeguindo) {
            Jtimeline.setText("Usuário Protegido!\nOs Tweets não podem ser exibidos.");
            jseguir.setText("Solicitar Seguir");
            Jseguidores.setEnabled(false);
            Jseguindo.setEnabled(false);
            Jtweets.setEnabled(false);
        } else {
            this.user = user;
            List<Status> statuses = null;

            statuses = tweetar.Timeline(conexao, user);

            if (statuses == null) {
                Jtimeline.setText("Você está impedido de seguir ou ver os tweets de " + user.getScreenName() + ".");
            } else {
                for (int i = 0; i < statuses.size(); i++) {
                    Status status = statuses.get(i);
                    Jtimeline.append(status.getUser().getName() + " : " + status.getText() + "\n");
                }
                Jtimeline.setCaretPosition(0);
            }
        }
    }

    public void Nome1(User usuario) throws TwitterException {
        Jseguindo.setText("<html>Seguindo<br>" + usuario.getFriendsCount());
        Jseguidores.setText("<html>Seguidores<br>" + usuario.getFollowersCount());
        Jtweets.setText("<html>Tweets<br>" + usuario.getStatusesCount());
        Jnome.setText(usuario.getName());
        Jnome2.setText("@"+usuario.getScreenName());
        jLabelPais.setText(usuario.getLocation());
        if (!usuario.isVerified()) {
            jLabelContaVerificada.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Jnome = new javax.swing.JLabel();
        Jtweets = new javax.swing.JButton();
        Jseguindo = new javax.swing.JButton();
        Jseguidores = new javax.swing.JButton();
        Jnome2 = new javax.swing.JLabel();
        Jimagem = new javax.swing.JLabel();
        jseguir = new javax.swing.JButton();
        jdeixar = new javax.swing.JButton();
        jLabelPais = new javax.swing.JLabel();
        jLabelContaVerificada = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Jtimeline = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Twitter for Java");
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Jnome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Jnome.setText("Nome");

        Jtweets.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Jtweets.setText("Tweets");
        Jtweets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtweetsActionPerformed(evt);
            }
        });

        Jseguindo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Jseguindo.setText("Seguindo");
        Jseguindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JseguindoActionPerformed(evt);
            }
        });

        Jseguidores.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Jseguidores.setText("Seguidor");
        Jseguidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JseguidoresActionPerformed(evt);
            }
        });

        Jnome2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Jnome2.setText("@Nome");

        jseguir.setText("Seguir");
        jseguir.setEnabled(false);
        jseguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jseguirActionPerformed(evt);
            }
        });

        jdeixar.setText("Deixar de Seguir");
        jdeixar.setEnabled(false);
        jdeixar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdeixarActionPerformed(evt);
            }
        });

        jLabelPais.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPais.setText("Localidade");

        jLabelContaVerificada.setText("Conta Verificada");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jtweets, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jimagem, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jdeixar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(Jseguindo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Jseguidores, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Jnome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Jnome2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelContaVerificada)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jseguir, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Jseguindo, Jtweets});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Jnome, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Jnome2)
                            .addComponent(jLabelContaVerificada))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelPais))
                    .addComponent(Jimagem, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jtweets)
                    .addComponent(Jseguindo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Jseguidores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jseguir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jdeixar))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Jtimeline.setEditable(false);
        Jtimeline.setColumns(20);
        Jtimeline.setRows(5);
        Jtimeline.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(Jtimeline);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jdeixarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdeixarActionPerformed
        try {
            tweetar.Deixar(conexao, user.getScreenName());
            jseguir.setEnabled(true);
            jdeixar.setEnabled(false);

            JOptionPane.showMessageDialog(null, "Voce deixou de seguir: " + user.getScreenName());
        } catch (TwitterException ex) {
            JOptionPane.showMessageDialog(null, "ERRO AO DEIXAR DE SEGUIR: " + user.getScreenName());
        }
    }//GEN-LAST:event_jdeixarActionPerformed

    private void jseguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jseguirActionPerformed
        try {
            tweetar.Seguir(conexao, user.getScreenName());
            jseguir.setEnabled(false);
            jdeixar.setEnabled(true);

            JOptionPane.showMessageDialog(null, "Voce está seguindo: " + user.getScreenName());
        } catch (TwitterException ex) {
            JOptionPane.showMessageDialog(null, "ERRO AO SEGUIR: " + user.getScreenName());
        }
    }//GEN-LAST:event_jseguirActionPerformed

    private void JseguidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JseguidoresActionPerformed
        User aux;
        try {
            lista = tweetar.Seguidores(conexao, user);
            Jtimeline.setText("Últimos 5 Seguidores de " + user.getScreenName() + "\n\n");
            for (i = 0; i < 5; i++) {
                aux = lista.get(i);
                Jtimeline.append(aux.getScreenName() + "\n");
            }
        } catch (TwitterException ex) {
            Logger.getLogger(TelaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JseguidoresActionPerformed

    private void JseguindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JseguindoActionPerformed
        User aux;
        try {
            lista = tweetar.Seguindo(conexao, user);
            Jtimeline.setText("Últimos 5 usuários seguidos\n\n");
            for (i = 0; i < 5; i++) {
                aux = lista.get(i);
                Jtimeline.append(aux.getScreenName() + "\n");
            }
        } catch (TwitterException ex) {
            Logger.getLogger(TelaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JseguindoActionPerformed

    private void JtweetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtweetsActionPerformed
        try {
            Jtimeline.setText("");
            PreencherTime(user);
        } catch (TwitterException ex) {
            Logger.getLogger(TelaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JtweetsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaUsuario dialog = new TelaUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jimagem;
    private javax.swing.JLabel Jnome;
    private javax.swing.JLabel Jnome2;
    private javax.swing.JButton Jseguidores;
    private javax.swing.JButton Jseguindo;
    private javax.swing.JTextArea Jtimeline;
    private javax.swing.JButton Jtweets;
    private javax.swing.JLabel jLabelContaVerificada;
    private javax.swing.JLabel jLabelPais;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jdeixar;
    private javax.swing.JButton jseguir;
    // End of variables declaration//GEN-END:variables
}
